### ISSUE TITLE
Add some more ships 

### ISSUE THREAD

**Issue by OrnicarLichess** [DakshCodess/OnlineAlienGame#30]
@DakshCodess , the game is awesome . But you should add some more ships in it . It would be great work if you add some more ships on over the game . Hope you like my idea .

**Comment by DakshCodess** [comment]
Hmm , thx for forking over this git repository . About being add some more ships , so i am thinking to add some more ships . You'r issue is great . Hope you bring more ideas as an issue you'r work will be done soon.
